#!/bin/sh
set -e

if ! [ -d config ]; then
	rm -rf config
	cp -r /opt/kavita/config config
fi

if ! [ -h wwwroot ]; then
	rm -rf wwwroot
	ln -s /opt/kavita/wwwroot wwwroot
fi

if ! [ -h EmailTemplates ]; then
	rm -rf EmailTemplates
	ln -s /opt/kavita/EmailTemplates EmailTemplates
fi

exec /opt/kavita/Kavita
